---
- hosts: localhost
  connection: local
  gather_facts: yes

  roles:
     - role: aws-ec2
       ec2_server_instcount: 1
       ec2_server_instance_type: 't2.micro'
       ec2_server_image: 'ami-003634241a8fcdec0'
       ec2_server_region: 'us-west-2'
       ec2_server_subnet: 'subnet-0f87fc01fe2e651b6'
       ec2_server_security_group: 'sg-0e41b3216ce450425'
       ec2_server_name: 'Test01ByAnsible'
       ec2_server_keypair: 'Managed-Key'
       ec2_server_access_key: '{{ lookup("env","AWS_ACCESS_KEY") }}' # export AWS_ACCESS_KEY="XXXXXXXXXXX"
       ec2_server_secret_key: '{{ lookup("env","AWS_SECRET_KEY") }}' # export AWS_SECRET_KEY="XXXXXXXXXXXXXXXXXXXX"
